# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sim_engine_pb2 as sim__engine__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sim_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunScenario = channel.unary_stream(
                '/agd.sim.SimEngine/RunScenario',
                request_serializer=sim__engine__pb2.SimRequest.SerializeToString,
                response_deserializer=sim__engine__pb2.SimEvent.FromString,
                _registered_method=True)
        self.PauseRun = channel.unary_unary(
                '/agd.sim.SimEngine/PauseRun',
                request_serializer=sim__engine__pb2.RunRef.SerializeToString,
                response_deserializer=sim__engine__pb2.RunStatus.FromString,
                _registered_method=True)
        self.ResumeRun = channel.unary_unary(
                '/agd.sim.SimEngine/ResumeRun',
                request_serializer=sim__engine__pb2.RunRef.SerializeToString,
                response_deserializer=sim__engine__pb2.RunStatus.FromString,
                _registered_method=True)
        self.StepTurn = channel.unary_unary(
                '/agd.sim.SimEngine/StepTurn',
                request_serializer=sim__engine__pb2.RunRef.SerializeToString,
                response_deserializer=sim__engine__pb2.SimEvent.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/agd.sim.SimEngine/GetState',
                request_serializer=sim__engine__pb2.RunRef.SerializeToString,
                response_deserializer=sim__engine__pb2.SimState.FromString,
                _registered_method=True)
        self.InjectEvent = channel.unary_unary(
                '/agd.sim.SimEngine/InjectEvent',
                request_serializer=sim__engine__pb2.EventInjection.SerializeToString,
                response_deserializer=sim__engine__pb2.Ack.FromString,
                _registered_method=True)


class SimEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunScenario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StepTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InjectEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunScenario': grpc.unary_stream_rpc_method_handler(
                    servicer.RunScenario,
                    request_deserializer=sim__engine__pb2.SimRequest.FromString,
                    response_serializer=sim__engine__pb2.SimEvent.SerializeToString,
            ),
            'PauseRun': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseRun,
                    request_deserializer=sim__engine__pb2.RunRef.FromString,
                    response_serializer=sim__engine__pb2.RunStatus.SerializeToString,
            ),
            'ResumeRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeRun,
                    request_deserializer=sim__engine__pb2.RunRef.FromString,
                    response_serializer=sim__engine__pb2.RunStatus.SerializeToString,
            ),
            'StepTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.StepTurn,
                    request_deserializer=sim__engine__pb2.RunRef.FromString,
                    response_serializer=sim__engine__pb2.SimEvent.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=sim__engine__pb2.RunRef.FromString,
                    response_serializer=sim__engine__pb2.SimState.SerializeToString,
            ),
            'InjectEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.InjectEvent,
                    request_deserializer=sim__engine__pb2.EventInjection.FromString,
                    response_serializer=sim__engine__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agd.sim.SimEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agd.sim.SimEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agd.sim.SimEngine/RunScenario',
            sim__engine__pb2.SimRequest.SerializeToString,
            sim__engine__pb2.SimEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agd.sim.SimEngine/PauseRun',
            sim__engine__pb2.RunRef.SerializeToString,
            sim__engine__pb2.RunStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agd.sim.SimEngine/ResumeRun',
            sim__engine__pb2.RunRef.SerializeToString,
            sim__engine__pb2.RunStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StepTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agd.sim.SimEngine/StepTurn',
            sim__engine__pb2.RunRef.SerializeToString,
            sim__engine__pb2.SimEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agd.sim.SimEngine/GetState',
            sim__engine__pb2.RunRef.SerializeToString,
            sim__engine__pb2.SimState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InjectEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agd.sim.SimEngine/InjectEvent',
            sim__engine__pb2.EventInjection.SerializeToString,
            sim__engine__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
