apiVersion: v1
kind: ConfigMap
metadata:
  name: agd-config
  namespace: {{ include "agd.namespace" . }}
  labels:
    {{- include "agd.labels" . | nindent 4 }}
data:
  ENV: "production"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  REDIS_URL: "redis://redis:6379"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  OLLAMA_URL: "http://ollama:11434"
  KEYCLOAK_URL: "http://keycloak:8080"
  TILE_SERVER_URL: "http://mbtiles-server:8080"
  AIRGAP: {{ .Values.airgap | quote }}
  CLASSIFICATION_LEVEL: {{ .Values.classificationLevel | quote }}
  AUTH_SVC_URL: "http://auth-svc:8082"
