---
apiVersion: v1
kind: Service
metadata:
  name: mbtiles-server
  namespace: {{ include "agd.namespace" . }}
  labels:
    {{- include "agd.labels" . | nindent 4 }}
    app.kubernetes.io/name: mbtiles-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/name: mbtiles-server
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbtiles-server
  namespace: {{ include "agd.namespace" . }}
  labels:
    {{- include "agd.labels" . | nindent 4 }}
    app.kubernetes.io/name: mbtiles-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mbtiles-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mbtiles-server
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mbtiles-server
          image: {{ include "agd.image" (dict "img" .Values.mbtiles.image "context" .) }}
          imagePullPolicy: {{ .Values.mbtiles.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tilesets
              mountPath: /tilesets
          resources:
            {{- toYaml .Values.mbtiles.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /services
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: tilesets
          emptyDir: {}
