apiVersion: v1
kind: Secret
metadata:
  name: agd-secrets
  namespace: {{ include "agd.namespace" . }}
  labels:
    {{- include "agd.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwt.secret | quote }}
  db-password: {{ .Values.postgres.password | quote }}
  keycloak-admin-password: {{ .Values.keycloak.adminPassword | quote }}
